version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_dbname
    ports:
      - "5432:5432"
